### ISSUE TITLE
Use `systemctl` instead of `service`

### ISSUE THREAD

**Issue by drebatto** [EGI-Federation/glite-info-provider-service#6]
Hi,

in **glite-info-service-status**, the command `service $SERVICE status` is still used to populate, for example, **GLUE2EndpointHealthStateInfo**. On recent Red Hat releases, this is translated into `systemctl status $SERVICE`, which results in some warnings in the log file and yields a somewhat unreadable output for the field:
```
GLUE2EndpointHealthStateInfo: * bdii.service - Berkeley Database Information I
 ndex      Loaded: loaded (/usr/lib/systemd/system/bdii.service; enabled; pres
 et: disabled)      Active: active (running) since Wed 2024-02-28 17:18:18 CET
 ; 49min ago        Docs: man:bdii-upd...4444
```
Would you consider replacing it e.g. with a `systemctl is-active` command?
https://github.com/EGI-Federation/glite-info-provider-service/blob/5e9e3f262256e0188c5e4063f8883160f7280160/src/glite-info-service-status#L21

**Comment by gwarf** [comment]
Hi, thanks for the report!
I don't think we will replace all the calls, unless someone makes a PR for it, or we have no other choice.
Instead, I will try to see if we could just add a dependency on initscripts-service, to avoid having to touch too much of the legacy code base.

**Comment by gwarf** [comment]
Please look at https://github.com/EGI-Federation/glite-info-provider-service/releases/tag/v1.14.1, thanks!
